-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Worlds.Hub.DungeonTemple:FindFirstChild("1").RaidRooms.Room4,
    [2] = "TargetWorld",
    [3] = "ChainsawRaid"
}

game:GetService("ReplicatedStorage").Remote.Raid.SetRaidSetting:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Worlds.Hub.DungeonTemple:FindFirstChild("1").RaidRooms.Room4
}

game:GetService("ReplicatedStorage").Remote.Raid.StartRaidFromRoom:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("ReplicatedStorage").UnloadedWorlds.Hub.DungeonTemple:FindFirstChild("1").RaidRooms.Room4,
    [2] = false
}

game:GetService("ReplicatedStorage").Remote.Raid.SetInRaid:FireServer(unpack(args))

6677,-113,6048

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Raids",
    [2] = "Hotel"
}

game:GetService("ReplicatedStorage").Remote.Player.Teleport:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Raids",
    [2] = "Train"
}

game:GetService("ReplicatedStorage").Remote.Player.Teleport:FireServer(unpack(args))
8294,-188,6294

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Worlds.Raids:FindFirstChild("1").Zone8.Chests.RaidChest2
}

game:GetService("ReplicatedStorage").Remote.Drops.OpenChest:InvokeServer(unpack(args))
