-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Worlds.OnePiece.OnePieceOrb,
    [2] = 5
}

game:GetService("ReplicatedStorage").Remote.Orbs.OpenOrbs:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "DBZSummon",
    [2] = workspace.Worlds.Hub.SecretArea:FindFirstChild("1").Trigger
}

game:GetService("ReplicatedStorage").Remote.Machines.SecretMachine:FireServer(unpack(args))

setconstant(do_open,17, 100)game:GetService("Players").LocalPlayer.PlayerGui.OrbGui.OrbGuiScriptgame:GetService("ReplicatedStorage").Remote.Orbs.OpenOrbsgame:GetService("Players").LocalPlayer.PlayerGui.OrbGui.OrbGuiScript